"""Speed/pitch editing.

The bug this file exists to stop is a one-liner that looks right: `atempo={rate}`.
ffmpeg's atempo takes **0.5–2.0 per instance**, so that form breaks on exactly the two
things a user reaches for first — 0.25x and 4x — and breaks by producing a filter graph
ffmpeg rejects (or, on some builds, silently clamps). :func:`tempo_chain` is therefore
the load-bearing part, and it is pure, so it is tested without touching ffmpeg.
"""

from __future__ import annotations

import math
import shutil
import subprocess
from pathlib import Path

import pytest

from navig.media.audio_edit import (
    AudioEditError,
    ffmpeg_available,
    probe_sample_rate,
    rate_filter,
    slowed,
    speed,
    tempo_chain,
    tempo_filter,
)

ATEMPO_MIN, ATEMPO_MAX = 0.5, 2.0


@pytest.mark.parametrize("rate", [0.25, 0.4, 0.5, 0.8, 1.0, 1.5, 2.0, 3.0, 4.0, 16.0, 0.1])
def test_every_factor_is_in_ffmpegs_window_and_the_product_is_the_request(rate):
    factors = tempo_chain(rate)
    assert factors, "a rate must always produce at least one factor"
    for f in factors:
        assert ATEMPO_MIN <= f <= ATEMPO_MAX, f"{f} is outside ffmpeg's atempo window"
    assert math.isclose(math.prod(factors), rate, rel_tol=1e-6), (
        f"{factors} multiplies to {math.prod(factors)}, not {rate} — the audio would come "
        f"out at the wrong speed"
    )


def test_the_two_rates_a_naive_implementation_gets_wrong():
    # A single `atempo=0.25` / `atempo=4` is rejected by ffmpeg. These must chain.
    assert tempo_chain(0.25) == [0.5, 0.5]
    assert tempo_chain(4.0) == [2.0, 2.0]
    assert tempo_filter(0.25) == "atempo=0.5,atempo=0.5"
    assert tempo_filter(4.0) == "atempo=2,atempo=2"


def test_an_in_range_rate_is_a_single_filter():
    # Anti-vacuity for the chaining test: the common case must NOT be split, or the
    # test above would pass while every ordinary 1.5x built a needless chain.
    assert tempo_chain(1.5) == [1.5]
    assert tempo_filter(1.5) == "atempo=1.5"


@pytest.mark.parametrize("bad", [0, -1, -0.5])
def test_a_non_positive_rate_is_refused_not_silently_clamped(bad):
    with pytest.raises(ValueError):
        tempo_chain(bad)
    with pytest.raises(ValueError):
        rate_filter(bad, 44100)


def test_pitch_shifting_filter_restores_a_normal_sample_rate():
    # asetrate alone leaves the stream claiming a nonstandard rate; without the
    # aresample some encoders refuse it and some players re-speed it.
    f = rate_filter(0.85, 44100)
    assert f == "asetrate=37485,aresample=44100"


def test_rate_filter_rejects_a_nonsense_sample_rate():
    with pytest.raises(ValueError):
        rate_filter(0.85, 0)


def test_a_missing_sample_rate_is_an_error_not_a_guess(tmp_path, monkeypatch):
    # Guessing 44100 would change the SPEED as well as the pitch — a plausible-sounding
    # wrong answer, which is worse than a refusal.
    import navig.media.audio_edit as editing

    src = tmp_path / "not-audio.bin"
    src.write_bytes(b"\x00" * 32)
    monkeypatch.setattr(editing.shutil, "which", lambda name: "ffprobe" if name == "ffprobe" else None)

    class _Out:
        stdout = "\n"

    monkeypatch.setattr(editing.subprocess, "run", lambda *a, **k: _Out())
    with pytest.raises(AudioEditError, match="sample rate"):
        probe_sample_rate(src)


def test_missing_ffmpeg_says_how_to_install_it(tmp_path, monkeypatch):
    import navig.media.audio_edit as editing

    monkeypatch.setattr(editing.shutil, "which", lambda _name: None)
    src = tmp_path / "a.wav"
    src.write_bytes(b"RIFF")
    with pytest.raises(AudioEditError, match="not installed|not on PATH"):
        speed(src, tmp_path / "out.wav", 1.5)


def test_exit_zero_with_no_output_is_still_a_failure(tmp_path, monkeypatch):
    """ffmpeg can exit 0 having written nothing. Reporting success for a file that is
    not there is the phantom-success shape; it must raise."""
    import navig.media.audio_edit as editing

    monkeypatch.setattr(editing.shutil, "which", lambda _name: "ffmpeg")

    class _Ok:
        returncode = 0
        stderr = ""

    monkeypatch.setattr(editing.subprocess, "run", lambda *a, **k: _Ok())
    src = tmp_path / "a.wav"
    src.write_bytes(b"RIFF")
    with pytest.raises(AudioEditError, match="wrote no audio"):
        speed(src, tmp_path / "missing.wav", 1.5)


# ── the real thing, when ffmpeg is present ────────────────────────────────────

requires_ffmpeg = pytest.mark.skipif(not ffmpeg_available(), reason="ffmpeg not on PATH")


@pytest.fixture()
def tone(tmp_path: Path) -> Path:
    """Two seconds of a real, decodable tone — generated by ffmpeg itself."""
    out = tmp_path / "tone.wav"
    subprocess.run(
        [shutil.which("ffmpeg"), "-nostdin", "-y", "-f", "lavfi",
         "-i", "sine=frequency=440:duration=2", str(out)],
        capture_output=True, check=True, timeout=60,
    )
    return out


def _duration(path: Path) -> float:
    out = subprocess.run(
        [shutil.which("ffprobe"), "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(path)],
        capture_output=True, text=True, check=True, timeout=60,
    )
    return float(out.stdout.strip())


@requires_ffmpeg
def test_speeding_up_actually_shortens_the_file(tone, tmp_path):
    out = tmp_path / "fast.wav"
    speed(tone, out, 2.0)
    assert out.exists() and out.stat().st_size > 0
    assert _duration(out) == pytest.approx(_duration(tone) / 2, rel=0.1)


@requires_ffmpeg
def test_a_chained_rate_is_applied_in_full(tone, tmp_path):
    """0.25x is the case the naive one-liner gets wrong — prove the whole factor lands,
    not just the first 0.5."""
    out = tmp_path / "quarter.wav"
    speed(tone, out, 0.25)
    assert _duration(out) == pytest.approx(_duration(tone) * 4, rel=0.1)


@requires_ffmpeg
def test_slowed_lengthens_it_too(tone, tmp_path):
    out = tmp_path / "slow.wav"
    result = slowed(tone, out, 0.5, reverb=False)
    assert result.pitch_shifted is True
    assert _duration(out) == pytest.approx(_duration(tone) * 2, rel=0.1)


@requires_ffmpeg
def test_reverb_still_produces_playable_audio(tone, tmp_path):
    out = tmp_path / "slow-reverb.wav"
    slowed(tone, out, 0.85, reverb=True)
    assert _duration(out) > 0
