"""doctor must name a declared-but-missing navig engine.

An editable install does not pick up dependencies added to pyproject after it
was made, so a package can be declared and absent simultaneously. navig-vault
went missing that way and the Telegram surface reported "api_id/api_hash are
not set" -- sending the operator to re-authenticate over intact credentials.
"""
from __future__ import annotations

import sys
import types

import navig.commands.doctor as doc

PYPROJECT = '[project]\ndependencies = ["navig-vault>=0.6.0", "rich>=13"]\n'
PYPROJECT_NO_ENGINES = '[project]\ndependencies = ["rich>=13", "typer>=0.12"]\n'


def _decl(names, source="pyproject"):
    return lambda: (names, source)


def _fake_tree(tmp_path, monkeypatch, body):
    pkg = tmp_path / "navig"
    pkg.mkdir()
    (pkg / "__init__.py").write_text("", encoding="utf-8")
    (tmp_path / "pyproject.toml").write_text(body, encoding="utf-8")
    monkeypatch.setitem(sys.modules, "navig",
                        types.SimpleNamespace(__file__=str(pkg / "__init__.py")))


def test_all_engines_importable_reports_ok(monkeypatch):
    monkeypatch.setattr(doc, "_declared_navig_engines", _decl(["navig-vault"]))
    monkeypatch.setattr(doc.importlib, "import_module", lambda _m: object())
    (row,) = doc.check_hard_dependencies()
    assert row[1]
    assert "all importable" in row.detail


def test_a_missing_engine_is_named(monkeypatch):
    monkeypatch.setattr(doc, "_declared_navig_engines", _decl(["navig-vault"]))

    def boom(_m):
        raise ImportError("No module named 'navig_vault'")
    monkeypatch.setattr(doc.importlib, "import_module", boom)
    (row,) = doc.check_hard_dependencies()
    assert not row[1]
    assert "navig-vault" in row.detail
    assert "pip install -e core" in row.detail


def test_unreadable_declarations_render_a_warning_not_a_tick(monkeypatch):
    """_check ignores warn= when ok is literally True, so "unknown" must not be ok."""
    monkeypatch.setattr(doc, "_declared_navig_engines", _decl([], ""))
    (row,) = doc.check_hard_dependencies()
    assert not row[1]
    assert "could not read" in row.detail


def test_pyproject_wins_over_installed_metadata(tmp_path, monkeypatch):
    """The dist-info is regenerated by whatever checkout last ran `pip install -e`.

    It can therefore be the stale artifact itself -- observed here, where the
    installed metadata had dropped navig-vault that pyproject still declared.
    Reading metadata first would make this check blind to its own reason to exist.
    """
    _fake_tree(tmp_path, monkeypatch, PYPROJECT)
    names, source = doc._declared_navig_engines()
    assert names == ["navig-vault"]
    assert source.endswith("pyproject.toml")


def test_third_party_deps_are_not_treated_as_engines(tmp_path, monkeypatch):
    _fake_tree(tmp_path, monkeypatch, PYPROJECT_NO_ENGINES)
    names, _ = doc._declared_navig_engines()
    assert names == []
