"""The site's committed snapshots describe the RELEASED navig — and can now say so.

navig.run documents whatever `web/www/content/cli-reference.generated.json` and
`bay-catalog.generated.json` hold. They are regenerated by every site build and meant to be
committed only at release, so what the site documents is what `pip install navig` ships.
Until now nothing could check that: cli-reference carried `sourceVersion` and called it
"the freshness signal", but that is commands.json's SCHEMA version (1.0.0 for every
release). Measured: the committed snapshot was July's (1,118 commands, 3.24.0-era) while
3.25.0 shipped on Sep 5 with 1,371 — the site under-documented the shipped release by 253
commands, and the hand-run release that propagated 3.25.0 to every manifest (b3527c2f5) did
not regenerate these, because no red light existed to say they were stale.

The builders now stamp `navigVersion` (from core/pyproject.toml at build time) and
`sourceCommit`. This guard compares the stamp to `core/latest.json`, the release manifest
the workflow publishes. It is an outside-file guard: editing any of the files it reads
selects it (INVARIANT_GUARDS), and it is in `sourceGuardArgs` so it runs on every change.

What it cannot see: a regen from `main` while main's pyproject version equals the released
one (the 13 days after a release before the next bump). `sourceCommit` is recorded for a
human — and for a stricter guard once release tags exist in this repo — and the builders'
⚠ notice (#1449) covers the local-regen case at the moment it happens.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]

RELEASE = REPO / "core" / "latest.json"
SNAPSHOTS = {
    "cli-reference": REPO / "web" / "www" / "content" / "cli-reference.generated.json",
    "bay-catalog (site)": REPO / "web" / "www" / "content" / "bay-catalog.generated.json",
    "bay-catalog (core)": REPO / "core" / "navig" / "data" / "bay-catalog.json",
}
WWW_LATEST = REPO / "web" / "www" / "public" / "latest.json"

# Structural anchor before trusting any read.
assert (REPO / "core" / "navig").is_dir(), REPO
assert RELEASE.is_file(), RELEASE


def _load(p: Path) -> dict:
    return json.loads(p.read_text(encoding="utf-8"))


def test_every_snapshot_is_stamped_with_the_navig_version_it_describes() -> None:
    for label, path in SNAPSHOTS.items():
        d = _load(path)
        assert d.get("navigVersion"), (
            f"{label} carries no navigVersion — it was generated by a builder older than the "
            f"stamp, so nothing can tell which release it documents. Regenerate at the release "
            f"commit: cd web/www && npm run sync:site"
        )


def test_every_snapshot_describes_the_released_version() -> None:
    released = _load(RELEASE)["version"]
    stale = {
        label: d.get("navigVersion")
        for label, path in SNAPSHOTS.items()
        if (d := _load(path)).get("navigVersion") != released
    }
    assert not stale, (
        f"navig.run would document a different navig than the one released ({released}): "
        f"{stale}. Regenerate the snapshots AT THE RELEASE COMMIT (cd web/www && npm run "
        f"sync:site) and commit them — that is the post-release step in core/docs/dev/release.md. "
        f"If a snapshot is AHEAD of the release, it was regenerated from an unreleased main: "
        f"`git checkout -- <file>` puts the site back on the shipped CLI."
    )


def test_the_site_and_core_release_manifests_agree() -> None:
    assert _load(WWW_LATEST)["version"] == _load(RELEASE)["version"]


def test_the_two_bay_catalog_copies_are_the_same_build() -> None:
    """The site copy and the core copy are written by one builder run; two different
    stamps means someone regenerated one and not the other."""
    site, core = _load(SNAPSHOTS["bay-catalog (site)"]), _load(SNAPSHOTS["bay-catalog (core)"])
    assert (site["navigVersion"], site.get("sourceCommit")) == (core["navigVersion"], core.get("sourceCommit"))


def test_the_schema_version_is_not_mistaken_for_the_freshness_signal() -> None:
    """`sourceVersion` is commands.json's schema version and identical across releases; the
    guard above must key on `navigVersion`. If someone ever makes sourceVersion track the
    navig version this passes too — the point is the two must not be confused."""
    d = _load(SNAPSHOTS["cli-reference"])
    assert "navigVersion" in d and "sourceVersion" in d
    assert d["navigVersion"] != "1.0.0" or d["sourceVersion"] != "1.0.0"
