"""Command→provider resolution — the suggest-and-activate flow.

When `navig <cmd>` is unknown (Typer exit code 2), `main.py` asks this module
whether a plugin provides `<cmd>` before falling back to "did you mean". Merge
order (first hit wins):

1. ``~/.navig/disabled_commands.json`` — installed-but-disabled beats everything
   (regenerated by ``PluginHost`` on every enable/disable);
2. the shipped map ``navig/data/command_providers.json`` (release-generated);
3. cached marketplace catalog files (never the network).

Everything here is imported ONLY on the error path or by the Store — nothing
loads on a successful invocation.
"""

from __future__ import annotations

import functools
import json
import logging
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_ACTIVATE_DEPTH_ENV = "NAVIG_ACTIVATE_DEPTH"


@dataclass
class ProviderInfo:
    command: str
    plugin: str
    pip: str | None = None
    module: str | None = None
    description: str = ""
    installed: bool = False      # installed but currently disabled
    canonical: str | None = None  # set when `command` is an alias


@functools.lru_cache(maxsize=1)
def _shipped_map() -> dict[str, Any]:
    # Release-generated, immutable at runtime — parse once per process.
    try:
        data_file = Path(__file__).resolve().parent.parent / "data" / "command_providers.json"
        data = json.loads(data_file.read_text(encoding="utf-8"))
        commands = data.get("commands", {})
        return commands if isinstance(commands, dict) else {}
    except Exception as exc:  # noqa: BLE001
        logger.debug("command_providers.json unreadable: %s", exc)
        return {}


def known_providers() -> dict[str, dict[str, Any]]:
    """plugin id → {description, pip, commands[]} from the shipped map.

    Feeds the Store's AVAILABLE rows — same source of truth as the
    suggest-and-activate flow.
    """
    providers: dict[str, dict[str, Any]] = {}
    for cmd, entry in _shipped_map().items():
        if not isinstance(entry, dict) or "alias_of" in entry:
            continue
        plugin = entry.get("plugin")
        if not plugin:
            continue
        info = providers.setdefault(plugin, {
            "description": entry.get("description", ""),
            "pip": entry.get("pip"),
            "module": entry.get("module"),
            "commands": [],
        })
        info["commands"].append(cmd)
    return providers


def resolve_provider(command: str) -> ProviderInfo | None:
    """Which plugin provides *command*? None when unknown."""
    # 1. Installed but disabled — the strongest signal.
    try:
        from navig.cli.registration import _disabled_command_map

        disabled = _disabled_command_map()
        if command in disabled:
            return ProviderInfo(command=command, plugin=disabled[command], installed=True)
    except Exception as exc:  # noqa: BLE001
        logger.debug("disabled-command lookup failed: %s", exc)

    # 2. Shipped map (aliases resolve to their canonical entry).
    shipped = _shipped_map()
    entry = shipped.get(command)
    canonical = None
    if isinstance(entry, dict) and "alias_of" in entry:
        canonical = str(entry["alias_of"])
        entry = shipped.get(canonical)
    if isinstance(entry, dict) and entry.get("plugin"):
        return ProviderInfo(
            command=command,
            plugin=str(entry["plugin"]),
            pip=entry.get("pip"),
            module=entry.get("module"),
            description=str(entry.get("description", "") or ""),
            canonical=canonical,
        )

    # 3. Cached marketplace catalogs (registered marketplaces' entries carrying
    #    a `commands` list; local files only — never the network here).
    try:
        from navig.plugins.marketplace import MarketplaceStore

        for row in MarketplaceStore().list_marketplaces():
            for mkt_entry in getattr(row, "entries", []) or []:
                commands = getattr(mkt_entry, "commands", None) or []
                if command in commands:
                    return ProviderInfo(
                        command=command,
                        plugin=mkt_entry.name,
                        description=mkt_entry.description or "",
                    )
    except Exception as exc:  # noqa: BLE001
        logger.debug("marketplace provider lookup failed: %s", exc)

    return None


def suggest_provider(command: str, argv: list[str]) -> bool:
    """Explain an unknown command that a plugin provides; offer activation.

    Returns True when a suggestion was printed (caller then skips did-you-mean).
    Interactive on a TTY: confirm → enable/install → offer to re-run the
    original command. Non-interactive / --json: print the hint, keep exit 2.
    """
    info = resolve_provider(command)
    if info is None:
        return False

    json_mode = "--json" in argv
    if json_mode:
        payload = {
            "error": "unknown_command",
            "command": command,
            "provider": {
                "plugin": info.plugin,
                "installed": info.installed,
                "pip": info.pip,
                "description": info.description,
            },
            "activate": (
                f"navig plugin enable {info.plugin}"
                if info.installed else f"navig store install {info.plugin}"
            ),
        }
        print(json.dumps(payload))
        return True

    from navig import console_helper as ch

    status = "installed, currently disabled" if info.installed else "not installed"
    ch.info(f"'{command}' is provided by plugin [bold]{info.plugin}[/bold] ({status})")
    if info.description:
        ch.dim(f"  {info.description}")

    interactive = sys.stdin.isatty() and sys.stdout.isatty()
    depth = int(os.environ.get(_ACTIVATE_DEPTH_ENV, "0") or 0)
    if not interactive or depth >= 1:
        verb = f"navig plugin enable {info.plugin}" if info.installed else f"navig store install {info.plugin}"
        ch.dim(f"  Activate: {verb}")
        return True

    import typer

    try:
        if info.installed:
            if not typer.confirm(f"Enable {info.plugin} now?", default=True):
                return True
            from navig.plugins.host import get_plugin_host

            get_plugin_host().enable(info.plugin)
            ch.success(f"Plugin '{info.plugin}' enabled")
        else:
            if not typer.confirm(f"Install {info.plugin} now?", default=True):
                return True
            _install(info)
    except Exception as exc:  # noqa: BLE001
        ch.error("Activation failed", str(exc)[:300])
        return True

    if typer.confirm(f"Re-run `{' '.join(argv[1:])}`?", default=True):
        env = dict(os.environ)
        env[_ACTIVATE_DEPTH_ENV] = str(depth + 1)
        result = subprocess.run([sys.executable, "-m", "navig.main", *argv[1:]], env=env)
        raise SystemExit(result.returncode)
    return True


def pip_install(package: str) -> None:
    """Install *package* into THIS interpreter's environment, runtime-aware.

    The shipped NAVIG runtime is a bare `uv venv` (no pip module), so
    `python -m pip` only works in dev checkouts. Order: importable pip →
    `uv pip install --python <this python>` (uv from PATH or the runtime dir)
    → actionable error. Raises ValueError with a user-facing message.
    """
    import importlib.util
    import shutil

    if importlib.util.find_spec("pip") is not None:
        cmd = [sys.executable, "-m", "pip", "install", package]
    else:
        uv = shutil.which("uv")
        if uv is None:
            runtime_uv = Path.home() / ".navig" / "runtime" / (
                "uv.exe" if os.name == "nt" else "uv"
            )
            uv = str(runtime_uv) if runtime_uv.exists() else None
        if uv is None:
            raise ValueError(
                f"Cannot install '{package}': this Python has no pip and uv was not "
                f"found — install manually into {sys.executable}"
            )
        cmd = [uv, "pip", "install", "--python", sys.executable, package]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True)
    except OSError as exc:  # spawn failure (missing/quarantined binary, perms)
        raise ValueError(
            f"Could not run the installer for '{package}': {exc}. "
            f"Install it manually into {sys.executable}."
        ) from exc
    if result.returncode != 0:
        detail = (result.stderr or result.stdout or "").strip()[:300]
        raise ValueError(f"install of '{package}' failed: {detail}")


def install_plugin_by_name(name: str, *, pip_name: str | None = None) -> str:
    """Install a plugin by name: host (dir/zip/git/marketplace) first, then the
    pip distribution from the command-provider map. Returns a success message;
    raises ValueError with a user-facing message. Shared by the Store's install
    action, `navig store install`, and the suggest-and-activate flow.
    """
    from navig.plugins.host import get_plugin_host

    try:
        dest = get_plugin_host().install(name)
        return f"Installed '{dest.name}'"
    except ValueError as host_err:
        pkg = pip_name or known_providers().get(name, {}).get("pip")
        if not pkg:
            raise ValueError(
                f"{host_err} No pip source is known for '{name}' either."
            ) from host_err
        pip_install(pkg)
        return f"Installed '{pkg}' via pip — restart the CLI to pick up its commands"


def _install(info: ProviderInfo) -> None:
    """Install the providing plugin — host sources first, else its pip dist.

    NOTE: first-party plugins not yet published to PyPI will fail here with a
    clear error; the pip name comes from the signed release map, never from
    user input, which bounds the dependency-confusion surface.
    """
    from navig import console_helper as ch

    ch.success(install_plugin_by_name(info.plugin, pip_name=info.pip))
