"""navig sync instructions — the cross-platform port of sync-instructions.ps1.

The load-bearing test is `test_matches_committed_mirrors`: it proves the Python transform
produces byte-identical output to what the PowerShell script wrote (the committed
.cursorrules / copilot-instructions.md), so switching to `navig sync instructions` can't
silently reformat the mirrors. The rest pin the transform rules and the .vscode safety.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from navig.core import instruction_sync as s

_REPO_ROOT = Path(__file__).resolve().parents[3]


# ── the transform ────────────────────────────────────────────────────────────

def test_strips_yaml_front_matter():
    raw = ["---", "applyTo: '**'", "---", "# Title", "body"]
    assert s.process(raw, "cursor") == "# Title\nbody"


def test_removes_section_tagged_for_this_target_only():
    raw = [
        "## Keep",
        "kept",
        "## Drop <!-- SKIP:cursor -->",
        "dropped",
        "## After",
        "after",
    ]
    # cursor: the SKIP:cursor section (and its heading) is gone; the rest stays.
    assert s.process(raw, "cursor") == "## Keep\nkept\n## After\nafter"
    # copilot: nothing skipped — but the inline SKIP tag is stripped from the heading.
    assert "## Drop" in s.process(raw, "copilot")
    assert "SKIP:cursor" not in s.process(raw, "copilot")


def test_multi_skip_heading_is_dropped_for_each_named_target():
    raw = ["## Roster <!-- SKIP:cursor SKIP:cline -->", "x", "## Next", "y"]
    assert "Roster" not in s.process(raw, "cursor")
    assert "Roster" not in s.process(raw, "cline")
    # A target NOT named keeps the section (faithful to the PS1: the multi-tag survives).
    assert "Roster" in s.process(raw, "copilot")


def test_strips_full_line_comments_and_trailing_blanks():
    raw = ["a", "<!-- a note -->", "b", "", "  "]
    assert s.process(raw, "cursor") == "a\nb"


def test_no_trailing_newline():
    assert not s.process(["a", "b"], "cursor").endswith("\n")


# ── byte-parity with the PowerShell script's committed output ────────────────

@pytest.mark.parametrize("target", ["cursor", "copilot"])
def test_matches_committed_mirrors(target):
    """The Python transform must reproduce the committed (PS1-generated) mirror exactly."""
    master = _REPO_ROOT / s.MASTER_REL
    mirror = _REPO_ROOT / s.TARGET_PATHS[target]
    if not master.is_file() or not mirror.is_file():
        pytest.skip("running outside the labs repo")
    raw = master.read_text(encoding="utf-8").splitlines()
    expected = mirror.read_text(encoding="utf-8").replace("\r\n", "\n")
    assert s.process(raw, target) == expected, (
        f"{s.TARGET_PATHS[target]} would change if regenerated by navig sync instructions — "
        "the port diverged from sync-instructions.ps1."
    )


def test_check_drift_reports_in_sync_for_the_repo():
    if not (_REPO_ROOT / s.MASTER_REL).is_file():
        pytest.skip("running outside the labs repo")
    states = dict(s.check_drift(_REPO_ROOT))
    assert states[".cursorrules"] == "in sync"
    assert states[".github/copilot-instructions.md"] == "in sync"


# ── the .vscode/settings.json safety (never clobber user keys) ───────────────

def test_vscode_injection_preserves_every_other_key():
    existing = json.dumps({
        "workbench.colorTheme": "Tomorrow Night Blue",
        "editor.fontSize": 14,
        "github.copilot.chat.codeGeneration.instructions": [{"text": "OLD"}],
    })
    out, status = s._inject_vscode(existing, "NEW INSTRUCTIONS")
    assert status == "written"
    data = json.loads(out)
    assert data["workbench.colorTheme"] == "Tomorrow Night Blue"  # untouched
    assert data["editor.fontSize"] == 14                          # untouched
    assert data["github.copilot.chat.codeGeneration.instructions"] == [{"text": "NEW INSTRUCTIONS"}]


def test_vscode_injection_tolerates_jsonc_comments():
    existing = '{\n  // my theme\n  "workbench.colorTheme": "X" /* inline */\n}'
    out, status = s._inject_vscode(existing, "T")
    assert status == "written"
    assert json.loads(out)["workbench.colorTheme"] == "X"


def test_vscode_unparseable_is_never_clobbered():
    out, status = s._inject_vscode("{ this is not: valid json", "T")
    assert status == "unparseable"
    assert out is None


def test_vscode_missing_file_creates_just_the_key():
    out, status = s._inject_vscode(None, "T")
    assert status == "written"
    assert json.loads(out) == {"github.copilot.chat.codeGeneration.instructions": [{"text": "T"}]}


# ── the writer (dry run + real) ──────────────────────────────────────────────

def test_dry_run_writes_nothing(tmp_path):
    (tmp_path / ".github" / "instructions").mkdir(parents=True)
    (tmp_path / s.MASTER_REL).write_text("---\nx: 1\n---\n# Hi\nbody\n", encoding="utf-8")
    results = s.sync_all(tmp_path, dry_run=True)
    assert all(status == "dry" for _rel, status, _n in results)
    assert not (tmp_path / ".cursorrules").exists()


def test_real_run_writes_all_targets(tmp_path):
    (tmp_path / ".github" / "instructions").mkdir(parents=True)
    (tmp_path / s.MASTER_REL).write_text("---\nx: 1\n---\n# Hi\nbody\n", encoding="utf-8")
    s.sync_all(tmp_path, dry_run=False)
    assert (tmp_path / ".cursorrules").read_text(encoding="utf-8") == "# Hi\nbody"
    assert (tmp_path / ".claude" / "CLAUDE.md").is_file()
    vs = json.loads((tmp_path / ".vscode" / "settings.json").read_text(encoding="utf-8"))
    assert vs["github.copilot.chat.codeGeneration.instructions"][0]["text"] == "# Hi\nbody"


def test_cline_mirror_is_wrapped(tmp_path):
    (tmp_path / ".github" / "instructions").mkdir(parents=True)
    (tmp_path / s.MASTER_REL).write_text("# Hi\nbody\n", encoding="utf-8")
    s.sync_all(tmp_path, dry_run=False)
    cline = (tmp_path / ".cline" / "memory.md").read_text(encoding="utf-8")
    assert cline.startswith("# NAVIG — Agent Memory")
    assert "Last synced:" in cline
    assert cline.rstrip().endswith("body")


# ── the repo it must find is the one you are STANDING in (2026-09-06) ────────
#
# `navig sync instructions --check`, run from inside the repo that holds MASTER,
# answered "Could not find MASTER instructions. Run inside a repo containing
# .github/instructions/MASTER.instructions.md" — advising the operator to do the
# thing they had just done. Cause: main.py chdirs the process into the ACTIVE
# SPACE before any command runs, so `_resolve_root` measured the space.
#
# Same class as the `navig repo --repo .` failure fixed alongside this, and
# doctor.py had already written the rule down: "main.py records the pre-chdir
# directory in NAVIG_INVOCATION_CWD for exactly this reason. Every repo-scoped
# check must resolve through here."
#
# ⚠ These build a REAL git repo under tmp_path. pytest's tmp_path lives inside
# the navig checkout's own .dev/ tree, so a plain directory would make
# `git rev-parse` climb out and resolve to the real repo — which HAS MASTER, so
# every assertion would pass against the wrong root (it did, first run).

import subprocess as _sp


def _make_repo(root: Path, *, master: bool = True) -> Path:
    root.mkdir(parents=True, exist_ok=True)
    _sp.run(["git", "init", "-q"], cwd=str(root), capture_output=True, check=True)
    if master:
        (root / s.MASTER_REL).parent.mkdir(parents=True, exist_ok=True)
        (root / s.MASTER_REL).write_text("# M\nbody\n", encoding="utf-8")
    return root


def test_resolve_root_finds_the_repo_you_invoked_from(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from navig.commands.sync import _resolve_root

    repo = _make_repo(tmp_path / "repo")
    space = tmp_path / "active-space"
    space.mkdir()

    monkeypatch.chdir(space)  # where main.py's chdir leaves us
    monkeypatch.setenv("NAVIG_INVOCATION_CWD", str(repo))

    assert _resolve_root(None) == repo


def test_resolve_root_walks_up_from_the_invocation_dir(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from navig.commands.sync import _resolve_root

    repo = _make_repo(tmp_path / "repo")
    nested = repo / "core" / "navig"
    nested.mkdir(parents=True)
    space = tmp_path / "active-space"
    space.mkdir()

    monkeypatch.chdir(space)
    monkeypatch.setenv("NAVIG_INVOCATION_CWD", str(nested))

    assert _resolve_root(None) == repo


def test_resolve_root_still_uses_cwd_without_the_env_var(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """No NAVIG_INVOCATION_CWD (a direct call, an embedding caller) — unchanged."""
    from navig.commands.sync import _resolve_root

    repo = _make_repo(tmp_path / "repo")
    monkeypatch.delenv("NAVIG_INVOCATION_CWD", raising=False)
    monkeypatch.chdir(repo)

    assert _resolve_root(None) == repo


def test_resolve_root_returns_none_when_neither_holds_master(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A genuine miss must stay a miss — the fix must not invent a root.

    Uses the SYSTEM temp dir, not tmp_path: the filesystem walk-up has no
    equivalent of GIT_CEILING_DIRECTORIES, so from inside the navig checkout it
    would legitimately climb to the real MASTER and this could never fail.
    """
    import tempfile

    from navig.commands.sync import _resolve_root

    # ignore_cleanup_errors: git can still hold a handle in the temp repo on
    # Windows, and a flaky teardown would discredit a test that is not flaky.
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as td:
        base = Path(td)
        a = _make_repo(base / "a", master=False)
        b = _make_repo(base / "b", master=False)
        monkeypatch.chdir(a)
        monkeypatch.setenv("NAVIG_INVOCATION_CWD", str(b))

        result = _resolve_root(None)
        monkeypatch.undo()  # leave the temp dir before it is removed (Windows)

    assert result is None


def test_explicit_repo_still_wins(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    from navig.commands.sync import _resolve_root

    repo = _make_repo(tmp_path / "repo")
    monkeypatch.setenv("NAVIG_INVOCATION_CWD", str(tmp_path / "elsewhere"))

    assert _resolve_root(str(repo)) == repo
