"""Regression tests for `navig script` — it must operate on config_dir()/scripts.

Sibling of #271/#276/#281: commands/script.py._get_scripts_dir() returned
``Path(__file__).parent.parent / "scripts"`` (= navig/scripts, INSIDE the package) while
ScriptEvolver (since #276), ahk.py, and mount.py all use ``config_dir()/scripts``. So
`navig script list/run/edit` could not see scripts generated by `navig evolve script`, and
`navig script new` wrote into the installed package (PermissionError on a read-only install,
lost on upgrade — the #189/#276 signature).
"""
from __future__ import annotations


class TestScriptsDir:
    def test_scripts_dir_is_config_dir_not_package(self, tmp_path, monkeypatch) -> None:
        monkeypatch.setenv("NAVIG_CONFIG_DIR", str(tmp_path))
        from navig.commands.script import _get_scripts_dir
        from navig.platform.paths import config_dir

        resolved = _get_scripts_dir()
        assert resolved == config_dir() / "scripts"
        assert resolved.is_absolute()
        # Must NOT resolve inside the installed package.
        assert "site-packages" not in str(resolved)
        assert resolved.name == "scripts" and resolved.parent == config_dir()

    def test_agrees_with_script_evolver(self, tmp_path, monkeypatch) -> None:
        """`navig script` and `navig evolve script` must target the SAME dir — the exact
        invariant that broke: the evolver moved to config_dir()/scripts (#276), this did not."""
        monkeypatch.setenv("NAVIG_CONFIG_DIR", str(tmp_path))
        from navig.commands.script import _get_scripts_dir
        from navig.core.evolution.script import ScriptEvolver

        assert _get_scripts_dir() == ScriptEvolver()._scripts_dir

    def test_resolution_touches_no_disk(self, tmp_path, monkeypatch) -> None:
        """Resolving the dir must not create it — only `script new` mkdirs on write."""
        monkeypatch.setenv("NAVIG_CONFIG_DIR", str(tmp_path))
        from navig.commands.script import _get_scripts_dir
        from navig.platform.paths import config_dir

        _get_scripts_dir()
        assert not (config_dir() / "scripts").exists()

    def test_honours_config_dir_isolation(self, tmp_path, monkeypatch) -> None:
        """Two brains (two NAVIG_CONFIG_DIRs) never share the scripts dir."""
        from navig.commands.script import _get_scripts_dir

        monkeypatch.setenv("NAVIG_CONFIG_DIR", str(tmp_path / "a"))
        a = _get_scripts_dir()
        monkeypatch.setenv("NAVIG_CONFIG_DIR", str(tmp_path / "b"))
        b = _get_scripts_dir()
        assert a != b
